include:
  - "_variables.yml"

variables:
  GIT_SSL_NO_VERIFY: "1"
  
image: gitlab-registry.insee.fr/datascience/registry-qf/onyxia-rstudio:r4.5.1

pages:
  tags :
   - docker

  script:
  - echo 'couleur du format choisie :'
  - echo $COULEURFORMAT
  - echo 'Deploy presentation to Gitlab pages'
  - Rscript -e 'install.packages(c("yaml", "jsonlite", "htmltools", "digest", "knitr", "rmarkdown", "dplyr", "DT", "plotly","leaflet","RColorBrewer","sf","gapminder"))'
  - Rscript -e 'print(getwd())'
  
#Pour modifier le format sur gitlab, modifier la valeur de cette variable dans le fichier _variables.yml
  - quarto render index.qmd --to insee-$COULEURFORMAT-revealjs
  
  - mkdir -p public # on cree le repertoire public
  - mv _output/* public/ # on copie les repertoires img et css (et leurs ss-rep) dans public
  artifacts:
    paths:
      - public
  only:
    - main
