# Comment faire un export du support de présentation ? {#chapters_5 .backgroundTitre_violet}

## PDF : Mode opératoire {#section_5_1 .backgroundStandard_violet}

:::{.enteteAvecTitre}
Comment faire un export du support de présentation ?
:::

- _étape 1 :_ Passer en mode export pdf
  - cliquer sur l'icône du menu : [{{< fa solid bars >}}]{style="color : '#3ea0e5';"} {{< fa solid arrow-right >}} sous-menu "Tools" {{< fa solid arrow-right >}} cliquer sur "PDF Export mode" ou taper directement sur la lettre "e" (raccourci)
  
::: {.callout-note}
Le mode export PDF est activé quand le support passe en navigation verticale (scrollable). Retaper sur "e" pour revenir au mode de navigation normal.
:::

- _étape 2 :_ Lancer l'export pdf
  - Dans la barre d'outils de votre navigateur: aller dans Fichier {{< fa solid arrow-right >}} Imprimer...
  - Dans la fenêtre qui s'ouvre :
    - sélectionner dans le champ destination "Enregistrer au format PDF"
    - cocher l'option "Imprimer les arrières plans"

## Autres formats {#section_5_2 .backgroundStandard}

:::{.enteteAvecTitre}
Comment faire un export du support de présentation ?
:::

Il est possible de faire des exports sous d'autres formats avec quarto, et de les cumuler au sein du projet. Par exemple, dans ce support, il est possible de faire un export (relativement sommaire) au format **.odt**, ouvrable avec la suite libreOffice. Pour ce faire :

- dans Rstudio, ouvrer le fichier .qmd, et cliquer sur la flèche déroulante acollée au bouton "render". Cliquer sur "Render odt".



::: {.callout-tip}
## Autres formats

Les formats sont listés et à configurer dans le fichier [_quarto.yml]{.bold}, ou dans le dossier extensions si vous décidez de custom un format existant, comme cela a été fait avec la charte Insee.
:::